---
- hosts: 172.31.45.3
  become: yes
  tasks:
    - include_tasks : myfilehandel.yml

    - name: i want to install apache2
      apt:
        name: apache2
        state: present

    - name: i want to copy file or alter file or create file in code
      template:
        src: myindex.j2
        dest: /var/www/html/index.html