---
- hosts: 172.31.36.118
  become: yes
  tasks:
    - name: i want to execute linux command
      command: hostname -f
      resister: myresult

    - name: i want to display linux output
      debug: 
        msg: "{{myresult}}"

    - name: i want to install tree
      apt:
        name: tree
        state: present
      when: myresult.stderr !=""

    - name: i want to wget
      apt:
        name: wget
        state: present
      when: myresult.stderr ==""